export const stateData = {
  "Andhra Pradesh": {
    capital: "Amaravati",
    population: "49.4 million",
    area: "162,975 km²",
    language: "Telugu",
    established: "1956",
  },
  "Arunachal Pradesh": {
    capital: "Itanagar",
    population: "1.4 million",
    area: "83,743 km²",
    language: "English, Bengali",
    established: "1987",
  },
  Assam: {
    capital: "Dispur",
    population: "31.2 million",
    area: "78,438 km²",
    language: "Assamese",
    established: "1950",
  },
  Bihar: {
    capital: "Patna",
    population: "104.1 million",
    area: "94,163 km²",
    language: "Hindi, Maithili",
    established: "1912",
  },
  Chhattisgarh: {
    capital: "Raipur",
    population: "25.5 million",
    area: "135,192 km²",
    language: "Hindi, Chhattisgarhi",
    established: "2000",
  },
  Goa: {
    capital: "Panaji",
    population: "1.5 million",
    area: "3,702 km²",
    language: "Konkani",
    established: "1987",
  },
  Gujarat: {
    capital: "Gandhinagar",
    population: "60.4 million",
    area: "196,024 km²",
    language: "Gujarati",
    established: "1960",
  },
  Haryana: {
    capital: "Chandigarh",
    population: "25.4 million",
    area: "44,212 km²",
    language: "Hindi, Haryanvi",
    established: "1966",
  },
  "Himachal Pradesh": {
    capital: "Shimla",
    population: "6.9 million",
    area: "55,673 km²",
    language: "Hindi, Pahari",
    established: "1971",
  },
  Jharkhand: {
    capital: "Ranchi",
    population: "32.9 million",
    area: "79,716 km²",
    language: "Hindi, Santali",
    established: "2000",
  },
  Karnataka: {
    capital: "Bengaluru",
    population: "61.1 million",
    area: "191,791 km²",
    language: "Kannada",
    established: "1956",
  },
  Kerala: {
    capital: "Thiruvananthapuram",
    population: "33.4 million",
    area: "38,852 km²",
    language: "Malayalam",
    established: "1956",
  },
  "Madhya Pradesh": {
    capital: "Bhopal",
    population: "72.6 million",
    area: "308,252 km²",
    language: "Hindi",
    established: "1956",
  },
  Maharashtra: {
    capital: "Mumbai",
    population: "112.4 million",
    area: "307,713 km²",
    language: "Marathi",
    established: "1960",
  },
  Manipur: {
    capital: "Imphal",
    population: "2.9 million",
    area: "22,327 km²",
    language: "Meitei",
    established: "1972",
  },
  Meghalaya: {
    capital: "Shillong",
    population: "3.0 million",
    area: "22,429 km²",
    language: "Khasi, Garo",
    established: "1972",
  },
  Mizoram: {
    capital: "Aizawl",
    population: "1.1 million",
    area: "21,081 km²",
    language: "Mizo",
    established: "1987",
  },
  Nagaland: {
    capital: "Kohima",
    population: "2.0 million",
    area: "16,579 km²",
    language: "English, Nagamese",
    established: "1963",
  },
  Odisha: {
    capital: "Bhubaneswar",
    population: "41.9 million",
    area: "155,707 km²",
    language: "Odia",
    established: "1936",
  },
  Punjab: {
    capital: "Chandigarh",
    population: "27.7 million",
    area: "50,362 km²",
    language: "Punjabi",
    established: "1966",
  },
  Rajasthan: {
    capital: "Jaipur",
    population: "68.5 million",
    area: "342,239 km²",
    language: "Hindi, Rajasthani",
    established: "1956",
  },
  Sikkim: {
    capital: "Gangtok",
    population: "0.6 million",
    area: "7,096 km²",
    language: "Nepali, Sikkimese",
    established: "1975",
  },
  "Tamil Nadu": {
    capital: "Chennai",
    population: "72.1 million",
    area: "130,058 km²",
    language: "Tamil",
    established: "1950",
  },
  Telangana: {
    capital: "Hyderabad",
    population: "35.0 million",
    area: "112,077 km²",
    language: "Telugu",
    established: "2014",
  },
  Tripura: {
    capital: "Agartala",
    population: "3.7 million",
    area: "10,486 km²",
    language: "Bengali, Kokborok",
    established: "1972",
  },
  "Uttar Pradesh": {
    capital: "Lucknow",
    population: "199.8 million",
    area: "240,928 km²",
    language: "Hindi",
    established: "1950",
  },
  Uttarakhand: {
    capital: "Dehradun",
    population: "10.1 million",
    area: "53,483 km²",
    language: "Hindi, Garhwali",
    established: "2000",
  },
  "West Bengal": {
    capital: "Kolkata",
    population: "91.3 million",
    area: "88,752 km²",
    language: "Bengali",
    established: "1947",
  },
  "Jammu & Kashmir": {
    capital: "Srinagar / Jammu",
    population: "12.5 million",
    area: "42,241 km²",
    language: "Kashmiri, Dogri, Urdu",
    established: "2019",
  },
  Ladakh: {
    capital: "Leh",
    population: "0.3 million",
    area: "59,146 km²",
    language: "Ladakhi, Hindi",
    established: "2019",
  },
  "Delhi (NCT)": {
    capital: "New Delhi",
    population: "16.8 million",
    area: "1,484 km²",
    language: "Hindi",
    established: "1991",
  },
  "Andaman & Nicobar": {
    capital: "Port Blair",
    population: "0.4 million",
    area: "8,249 km²",
    language: "Hindi, Bengali",
    established: "1956",
  },
  Chandigarh: {
    capital: "Chandigarh",
    population: "1.1 million",
    area: "114 km²",
    language: "Hindi, Punjabi",
    established: "1966",
  },
  "Dadra & Nagar Haveli and Daman & Diu": {
    capital: "Daman",
    population: "0.6 million",
    area: "603 km²",
    language: "Gujarati",
    established: "2020",
  },
  Lakshadweep: {
    capital: "Kavaratti",
    population: "0.064 million",
    area: "32 km²",
    language: "Malayalam",
    established: "1956",
  },
  Puducherry: {
    capital: "Puducherry",
    population: "1.2 million",
    area: "479 km²",
    language: "Tamil, French",
    established: "1954",
  },
};
